version: '3.3'

services:

  db:
    image: postgres:9.6
    container_name: nkdb
    ports:
      - '5434:5432'
    tty: true
    volumes:
      - .docker/.pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nkdb
      - POSTGRES_USER=nkpro
      - POSTGRES_PASSWORD=nkpro
      - POSTGRES_HOST=localhost

