# Generated by Django 3.2 on 2022-06-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0002_video_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(max_length=32),
        ),
    ]
