name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.4
          architecture: x64
          cache: 'pip'
      - name: Instalar dependências
        run: |
          pip install pipenv
          pipenv sync -d
      - name: Rodar flake8
        uses: py-actions/flake8@v1
        with:
          checkName: 'flake8_py3'
      - name: Rodar Testes Automáticos
        run: |
          pipenv run python -m pytest --cov=nkpro
      - name: Relatório Coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          pipenv run python -m codecov